apiVersion: v1
kind: ServiceAccount
metadata:
  name: grupo04-kong
  labels:
    app.kubernetes.io/name: grupo04-kong
    app.kubernetes.io/part-of: grupo04
  annotations:
    argocd.argoproj.io/sync-wave: "4"
