# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
import dataclasses
from typing import Any, Optional
import uuid


@dataclasses.dataclass()
class Message:
    id: uuid.UUID
    thread_id: uuid.UUID
    user_id: uuid.UUID
    type: Optional[Any]
    content: Optional[str]
    paths: Optional[Any]
    created_at: Optional[Any]
    updated_at: Optional[Any]
    deleted_at: Optional[Any]
