apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: messages-service
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: messages-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
