apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-config
  namespace: utfsm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  # Database
  DB_HOST: "database"
  DB_PORT: "5432"
  DB_USER: "root"
  DB_NAME: "messages_service"

  # Redis cache
  CACHE_ENABLED: "true"
  CACHE_TTL_SECONDS: "120"
  CACHE_MAX_ITEMS: "200"
  CACHE_TOUCH_ON_HIT: "true"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  # RabbitMQ queue
  QUEUE_HOST: "rabbitmq"
  QUEUE_PORT: "5672"
  QUEUE_USER: "root"
