apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chat-service
  namespace: utfsm
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chat-service
