name: Tests

on:
  push:
    paths:
      - 'service/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'service/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: service/requirements.txt

      - name: Install dependencies
        run: pip install -r service/requirements.txt

      - name: Run tests
        working-directory: service
        run: python -m pytest -q

